# Generated by Django 4.0.6 on 2022-07-31 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('cellphone', models.CharField(max_length=100)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('gest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guest')),
            ],
        ),
    ]
