# Generated by Django 4.0.6 on 2022-07-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companion_name_guest_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companion',
            old_name='gest',
            new_name='guest',
        ),
    ]
